solon.logging.appender:
  console:
    enable: false # 是否启用控制台日志（启用后，会对 cli console 有干扰）
  file:
    level: DEBUG

soloncode:
  tools: "**"
  maxSteps: 20 # ReAct 最大循环步数
  autoRethink: true #自我反思（每超过 maxSteps后，会由 LLM 自我反思决定是结束或继续）

  sessionWindowSize: 8 # 会话历史窗口大小（即，新指令时使用几条历史消息）

  summaryWindowSize: 40 # 触发摘要压缩的消息条数阈值（即，超过多少条就开始压缩）
  summaryWindowToken: 60_000 # 触发摘要压缩的内容长度阈值（即，超过多少长度就开始压缩）
#  summaryModel: "xxx"

  sandboxMode: true # 沙盒模式，启用时禁止访问绝对路径
  thinkPrinted: true # 内心思考，是否打印

  hitlEnabled: false # 是否启用人工审核危险操作，和 maxSteps 动态继步
  subagentEnabled: true # 是否启用子代理模式

  cliPrintSimplified: true # 控制台打印是否简化

  memoryEnabled: true # 是否启用心智记忆
  memoryIsolation: true # 心智记忆是否工作区隔离（如果隔离，每个工作区一份长记忆）

  userAgent: "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; SolonCode/1.0; +https://solon.noear.org/)"

  mountPools: # 技能池（可以多个）
    "@skills": "./skills/"
    "@skillhub": "~/.skillhub/skills/"
    "@agents_skills": "~/.agents/skills/"
    "@opencode_skills": "~/.opencode/skills/"
    "@claude_skills": "~/.claude/skills/"

  modelRetries: 5
  models: # llm 配置（参考 solon ai chatmodel 配置）
    - apiUrl: "https://api.deepseek.com/v1/chat/completions"
      apiKey: "******"
      model: "deepseek-v4-flash"
      timeout: "120s"
      contextLength: 1_000_000 # 模型的上下文长度
#      defaultOptions:
#        enable_thinking: false #不同模型可能不同
#        temperature: 0.2
#        top_p: 0.5
#        frequency_penalty: 0.5
#        presence_penalty: 0.4
#  apiRetries: 3
#  apiServers: # rest-api
#    api1:
#      docUrl: ""
#      apiBaseUrl: ""
#      headers: { API_KEY: "xxx" }
#  mcpRetries: 3
#  mcpServers: # mcp
#    gitee:
#      type: "streamable"
#      url: "http://..."
#      headers: { API_KEY: "xxx" }
#      timeout: "120s"
#    memory:
#      command: "npx"
#      args: [ "-y", "@modelcontextprotocol/server-memory" ]
#    lspServers:
#      java:
#        command: [ "jdtls", "-data", ".solon/lsp/java-workspace" ]
#        extensions: [ ".java" ]
#      python:
#        command: [ "pylsp" ]
#        extensions: [ ".py" ]
